# FIRST_TIME_SETUP.ps1
# Run this ONCE on each new computer before using ResearchTeam.
# Requirements: Windows 10/11 64-bit, internet connection, ~1 GB free disk space.

$ErrorActionPreference = "Stop"
$here = Split-Path -Parent $MyInvocation.MyCommand.Definition

Write-Host ""
Write-Host "=== ResearchTeam First-Time Setup ===" -ForegroundColor Cyan
Write-Host ""

# â”€â”€ Step 1: Check config.ini â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
if (-not (Test-Path "$here\config.ini")) {
    Write-Host "ERROR: config.ini not found. Cannot continue." -ForegroundColor Red
    pause; exit 1
}

$config = @{}
Get-Content "$here\config.ini" | ForEach-Object {
    if ($_ -match "^\s*([^#=\[\]]+?)\s*=\s*(.+)$") {
        $config[$Matches[1].Trim()] = $Matches[2].Trim()
    }
}

$apiKey    = $config["anthropic_api_key"]
$model     = $config["claude_model"]
$vault     = $config["vault_path"]
$vaultRoot = $config["vault_root"]

if ($apiKey -eq "sk-ant-REPLACE_WITH_YOUR_KEY" -or -not $apiKey) {
    Write-Host "ERROR: Edit config.ini and set your Anthropic API key first!" -ForegroundColor Red
    Write-Host "       Then run this script again." -ForegroundColor Yellow
    pause; exit 1
}

Write-Host "Config loaded OK." -ForegroundColor Green

# â”€â”€ Step 2: Locate or download Python â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
$pythonDir = "$here\python"
$pythonExe = "$pythonDir\python.exe"

if (Test-Path $pythonExe) {
    Write-Host "Python already present in .\python\" -ForegroundColor Green
} else {
    # Search for Python 3.10+ already on the machine
    $found = $null
    foreach ($candidate in @("python", "python3", "py")) {
        try {
            $v = & $candidate --version 2>&1
            if ("$v" -match "Python 3\.(1[0-9]|[89])") {
                $found = (Get-Command $candidate -ErrorAction SilentlyContinue)?.Source
                break
            }
        } catch {}
    }

    if ($found) {
        Write-Host "Using system Python: $found" -ForegroundColor Green
        $pythonExe = $found
    } else {
        Write-Host "Python not found - downloading Python 3.13 embeddable..." -ForegroundColor Yellow
        $pyVer = "3.13.3"
        $pyZip = "$here\python\_embed.zip"
        $url   = "https://www.python.org/ftp/python/$pyVer/python-$pyVer-embed-amd64.zip"
        New-Item -ItemType Directory -Force -Path $pythonDir | Out-Null
        Write-Host "  Downloading $url" -ForegroundColor Gray
        Invoke-WebRequest -Uri $url -OutFile $pyZip -UseBasicParsing
        Write-Host "  Extracting..." -ForegroundColor Gray
        Expand-Archive -Path $pyZip -DestinationPath $pythonDir -Force
        Remove-Item $pyZip

        # Enable site-packages inside the embeddable layout
        $pth = Get-ChildItem $pythonDir -Filter "python*._pth" | Select-Object -First 1
        if ($pth) {
            (Get-Content $pth.FullName) -replace "#import site", "import site" | Set-Content $pth.FullName
        }

        # Bootstrap pip
        Write-Host "  Bootstrapping pip..." -ForegroundColor Gray
        $getPip = "$pythonDir\_get-pip.py"
        Invoke-WebRequest -Uri "https://bootstrap.pypa.io/get-pip.py" -OutFile $getPip -UseBasicParsing
        & $pythonDir\python.exe $getPip --no-warn-script-location | Out-Null
        Remove-Item $getPip
    }
}

# Save resolved python path for launchers
$pythonExe | Set-Content "$here\.python_path" -Encoding UTF8
Write-Host "Python: $pythonExe" -ForegroundColor Gray

# â”€â”€ Step 3: Install packages â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
Write-Host ""
Write-Host "Installing packages (10-25 min on first run, needs internet)..." -ForegroundColor Yellow

$pkgs = @(
    "autogen-agentchat==0.5.7",
    "autogen-ext==0.5.7",
    "autogenstudio==0.4.2.2",
    "anthropic>=0.94.0",
    "wikipedia-api",
    "arxiv",
    "ddgs",
    "beautifulsoup4",
    "requests",
    "pymupdf4llm",
    "pdfplumber"
)
foreach ($pkg in $pkgs) {
    Write-Host "  pip install $pkg" -ForegroundColor Gray
    & $pythonExe -m pip install $pkg --quiet --no-warn-script-location
}
Write-Host "Packages installed." -ForegroundColor Green

# â”€â”€ Step 4: Generate research_config.py â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
Write-Host ""
Write-Host "Writing app\research_config.py..." -ForegroundColor Cyan
@"
# Auto-generated by FIRST_TIME_SETUP.ps1 from config.ini
ANTHROPIC_API_KEY = "$apiKey"
CLAUDE_MODEL      = "$model"
OBSIDIAN_VAULT    = r"$vault"
VAULT_ROOT        = r"$vaultRoot"
"@ | Set-Content "$here\app\research_config.py" -Encoding UTF8

# â”€â”€ Step 5: Register the AI team in the portable DB â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
$db = "$here\autogenstudio\autogen04202.db"
if (Test-Path $db) {
    Write-Host "Registering AI team in portable database..." -ForegroundColor Cyan
    & $pythonExe "$here\app\register_research_team.py" `
        --db "$db" `
        --vault "$vault" `
        --vault-root "$vaultRoot"
    Write-Host "Team registered." -ForegroundColor Green
} else {
    Write-Host "DB not found at $db - skipping team registration." -ForegroundColor Yellow
    Write-Host "Run: python app\register_research_team.py --db autogenstudio\autogen04202.db" -ForegroundColor Yellow
}

Write-Host ""
Write-Host "==================================================================" -ForegroundColor Green
Write-Host "  Setup complete!" -ForegroundColor Green
Write-Host "  Double-click START_AUTOGEN_STUDIO.bat to launch." -ForegroundColor Cyan
Write-Host "  Then open http://127.0.0.1:8080 in your browser." -ForegroundColor Cyan
Write-Host "==================================================================" -ForegroundColor Green
Write-Host ""
pause
